langauge: go
sudo: required
version:
  - 1.6

env:
  global:
    - CACHE_DIR=$HOME/.cache
    - XE_ZIP=oracle-xe-11.2.0-1.0.x86_64.rpm.zip

notifications:
  email: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends -qq install bc libaio1 rpm unzip
  - go get github.com/tschf/odl
  - bash .travis/oracle/download.sh

script:
  - ./test.sh
